# Generated by Django 6.0 on 2026-01-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_category_address_contactos_categoria_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='categorias',
        ),
        migrations.RenameModel(
            old_name='Address',
            new_name='enderecos',
        ),
        migrations.RenameModel(
            old_name='Note',
            new_name='nota',
        ),
    ]
